language: node_js
node_js:
  - "14.17.2"

cache:
  yarn: true
  directories: node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn test

before_deploy: "echo starting deploy!"
deploy:
  on:
    branch: master
  run: "echo must implement deploy script later!"
